#!/bin/bash

# modify kernel name in notebooks when using binder (see issue below)
# https://github.com/jupyterhub/binder/issues/152#issuecomment-469801364
sed -i 's/"Python (pylandstats-swiss-forests)"/"Python 3"/' notebooks/*.ipynb
sed -i 's/"name": "pylandstats-swiss-forests"/"name": "python3"/' notebooks/*.ipynb
